WebApplication1/Controllers/BooksController.cs
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using WebApplication1.Class;

namespace WebApplication1.Controllers
{
   
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index()
        {
            BookDao bookDao = new BookDao();
            IList<Book> books = bookDao.GetAll();

            return View(books);
        }


        public ActionResult Detail(int id) {

               BookDao bookDao = new BookDao();
            Book b = bookDao.GetById(id);

            return View(b);
        }


    }
}

WebApplication1/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
   

    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>       
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="@Url.Content("~/Content/black.css")" rel="stylesheet" type="text/css">

    <script src="@Url.Content("~/scripts/jquery-ui-1.12.1.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive-ajax.js")"></script>
    <script src="@Url.Content("~/scripts/MicrosoftAjax.js")"></script>
    <script src="@Url.Content("~/scripts/MicrosoftMvcAjax.js")"></script>

    <style>
        input.input-validation-error {
            background-color: plum;
        }
        input.valid {
            background-color: aquamarine;
        }
    </style>

</head>
<body>
 
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Main Page</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vypis knih", "Index", "Books", null, new {@class=""})</li>
                    
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Logout","Login")"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center" >
        <div class="row content">
            <div class="col-sm-2 sidenav">
                <p><a href="#">Link</a></p>
                <p><a href="#">Link</a></p>
                <p><a href="#">Link</a></p>
            </div>
            <div class="col-sm-8 text-left" id="dynamicContent">

                @RenderBody()



            </div>
            <div class="col-sm-2 sidenav">
                <div class="well">
                    <p>ADS</p>
                </div>
                <div class="well">
                    <p>ADS</p>
                </div>
            </div>
        </div>
    </div>




<footer class="container-fluid text-center" >
        <p>Footer Text</p>
    </footer>
<script src="@Url.Content("~/scripts/jquery.validate.js")"></script>    
<script src="@Url.Content("~/scripts/jquery.validate.unobtrusive.min.js")"></script>

<script src="@Url.Content("~/scripts/tinymce/tinymce.min.js")"></script>
    <script>tinymce.init({ selector:'.formatedtext' });</script>

</body>
</html>